import { Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 300px;
    height: 315px;
    title: "TimeKeeper";

    in-out property <int> remaining_secs: 1500;
    in-out property <string> timer_disp: "--:--";
    in-out property <string> period_name: "Work";
    in-out property <bool> is_timer_work: true;

    callback start_pause_clicked();
    callback stop_clicked();

    VerticalLayout {
        alignment: center;
        spacing: 5px;

        Text {
            text: period_name;
            font-size: 24px;
            horizontal-alignment: center;
        }

        Text {
            text: timer_disp;
            font-size: 24px;
            horizontal-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 5px;

            Button {
                text: is_timer_work ? "Pause" : "Start";
                clicked => start_pause_clicked();
            }

            Button {
                text: "Stop";
                clicked => stop_clicked();
            }
        }
    }
}
